name: Atualizar capa Público

on:
  schedule:
    - cron: "3 7 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Pull antes de tudo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main

      - name: Instalar dependências
        run: pip install requests beautifulsoup4

      - name: Executar script
        run: python baixar_publico_capa.py

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Atualizar capa Público automaticamente"
          file_pattern: publico-capa.jpg
          branch: main
