name: Atualizar capa CM

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Instalar dependências
        run: pip install requests beautifulsoup4

      - name: Executar script
        run: python baixar_capa.py

      - name: Pull antes de commit
        run: git pull --rebase origin main

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Atualizar capa CM automaticamente"
          file_pattern: correio-capa.jpg
          branch: main



