name: Atualizar capa

on:
  schedule:
    - cron: "0 8 * * *"   # todos os dias às 08:00 UTC
  workflow_dispatch:      # também podes rodar manualmente

jobs:
  update-capa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependências
        run: pip install requests beautifulsoup4

      - name: Executar script para gerar capa
        run: python baixar_capa.py

      - name: Commitar se houver alterações
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Atualizar capa automaticamente"
          file_pattern: correio-capa.jpg
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com


